/**
 * Rizen Signal Console — window runtime, client half.
 *
 * GENERATED by tools/gen-skin-client.mjs from the Harness personal theme
 * (packages/client/ui-theme/src/client/index.ts). Do not edit by hand:
 * change the source block there and re-run `npm run gen && npm run build`.
 *
 * The runtime is pure DOM code with no Harness imports. It gives every detail
 * surface — Think, tool output, Code — free placement, edge resizing,
 * click-to-front layering and cascade, while leaving the conversation column
 * exactly as wide as it was.
 */

/**
 * Every surface the window runtime treats as a floating window: the portalled
 * detail panels (Think, tool output, Code) and any in-flow code block the user
 * has detached. One constant keeps the installers from disagreeing about what a
 * window is; adding a surface means editing this line only.
 */
const WINDOW_SELECTOR = '[data-dsh-detail-panel], [class*="thinkBody"], [data-dsh-code-floating]'

/** The same surfaces, restricted to the ones parked in the dock. */
const WINDOW_MINIMIZED_SELECTOR = [
  '[data-dsh-detail-panel][data-dsh-panel-minimized="true"]',
  '[class*="thinkBody"][data-dsh-panel-minimized="true"]',
  '[data-dsh-code-floating][data-dsh-panel-minimized="true"]',
].join(', ')

/**
 * Add a short-lived hit marker at primary pointer clicks while the personal
 * arcade theme is active. Editable controls are excluded so placing a caret
 * never creates a combat effect over the text being composed.
 * @returns a disposer that removes the document listener.
 */
function installArcadePointerFeedback(): () => void {
  if (typeof document === 'undefined') return () => {}
  const onPointerDown = (event: PointerEvent): void => {
    if (event.button !== 0) return
    const target = event.target
    if (!(target instanceof Element) || target.closest("textarea, input, [contenteditable='true']") !== null) return
    const marker = document.createElement('span')
    marker.className = 'dsh-click-hit'
    marker.style.left = `${event.clientX}px`
    marker.style.top = `${event.clientY}px`
    marker.addEventListener('animationend', () => { marker.remove() }, { once: true })
    document.body.append(marker)
    window.setTimeout(() => { marker.remove() }, 720)
  }
  document.addEventListener('pointerdown', onPointerDown, true)
  return () => { document.removeEventListener('pointerdown', onPointerDown, true) }
}

/**
 * Keep expanded detail surfaces below the sticky composer as the viewport,
 * composer, or panel content changes. The measured value is presentation
 * state only; the panel keeps scrolling its own long body instead of
 * covering the input console. The composer's own height is republished as
 * `--dsh-composer-reserve` so the maximized window centers inside the band
 * above the input console. Detail panels never reserve width in the message
 * flow, so this pass never touches the transcript's geometry.
 * @returns a disposer for observers and listeners.
 */
function installArcadePanelLayout(): () => void {
  if (typeof document === 'undefined') return () => {}
  let frame: number | null = null
  let disposed = false
  const cascaded = new WeakSet<HTMLElement>()
  const sync = (): void => {
    if (disposed) return
    const composerTop = composerCeiling()
    document.documentElement.style.setProperty(
      '--dsh-composer-reserve',
      `${Math.max(0, Math.round(window.innerHeight - composerTop + PANEL_GAP))}px`,
    )
    // The conversation is the stage a maximized window belongs to. The sidebar
    // takes the left of the viewport, so centering on `50vw` reads as
    // off-centre to the eye; publish the stage's own centre and width instead.
    const stage = document.querySelector<HTMLElement>('[data-phase]')
    if (stage !== null) {
      const rect = stage.getBoundingClientRect()
      if (rect.width > 0) {
        document.documentElement.style.setProperty('--dsh-stage-centre', `${Math.round(rect.left + rect.width / 2)}px`)
        document.documentElement.style.setProperty('--dsh-stage-width', `${Math.round(rect.width)}px`)
      }
    }
    // The height ceiling belongs to the page, not to where a window happens to
    // sit: deriving it from the window's own top made dragging a window
    // downward shrink it. Placement keeps the composer clear instead.
    const safeHeight = `${Math.max(RESIZE_MIN_HEIGHT, Math.round(composerTop - PANEL_TOP_FLOOR - PANEL_GAP))}px`
    const panels = document.querySelectorAll<HTMLElement>(WINDOW_SELECTOR)
    for (const panel of panels) {
      const rect = panel.getBoundingClientRect()
      // A hidden or maximized panel owns its geometry: the maximized rule
      // centers inside the composer reserve, so a ceiling would only clip it.
      if (rect.width === 0 || rect.height === 0 || panel.hasAttribute('data-dsh-panel-maximized')) {
        panel.style.removeProperty('--dsh-panel-safe-height')
        continue
      }
      panel.style.setProperty('--dsh-panel-safe-height', safeHeight)
    }
    // Lay newly opened windows out on a diagonal, so several open details read
    // as separate windows instead of one exactly stacked pile. Each window is
    // offset once, the first time it appears.
    let opened = 0
    for (const panel of floatingWindows()) {
      if (panel.closest('[data-dsh-panel-pinned="true"]') === null && !cascaded.has(panel)) {
        cascaded.add(panel)
        panel.style.setProperty('--dsh-panel-cascade', `${Math.min(opened, CASCADE_LIMIT) * CASCADE_STEP}px`)
      }
      opened += 1
    }
  }
  const schedule = (): void => {
    // Observer callbacks can outlive the jsdom environment under vitest's
    // per-file environment switching; stay quiet once the DOM is gone.
    if (typeof window === 'undefined' || disposed || frame !== null) return
    frame = window.requestAnimationFrame(() => {
      frame = null
      sync()
    })
  }
  /* v8 ignore next -- jsdom provides no ResizeObserver, so the observer
     construction arm is unreachable under the unit suites. */
  const resizeObserver = typeof ResizeObserver === 'undefined' ? undefined : new ResizeObserver(schedule)
  const observe = (): void => {
    // Observer callbacks can outlive the jsdom environment under vitest's
    // per-file environment switching; stay quiet once the DOM is gone.
    if (typeof document === 'undefined') return
    resizeObserver?.disconnect()
    const composer = document.querySelector<HTMLElement>("[data-phase] [class*='composerSeat']")
    if (composer !== null) resizeObserver?.observe(composer)
    for (const panel of document.querySelectorAll<HTMLElement>(WINDOW_SELECTOR)) {
      resizeObserver?.observe(panel)
    }
  }
  /* v8 ignore next 3 -- every test host (jsdom and node) that provides
     document also provides MutationObserver, so this fallback arm is
     unreachable under the unit suites. */
  const mutationObserver = typeof MutationObserver === 'undefined'
    ? undefined
    : new MutationObserver(() => { observe(); schedule() })
  mutationObserver?.observe(document.body, { childList: true, subtree: true })
  observe()
  window.addEventListener('resize', schedule)
  document.addEventListener('scroll', schedule, true)
  schedule()
  return () => {
    disposed = true
    if (frame !== null) window.cancelAnimationFrame(frame)
    resizeObserver?.disconnect()
    mutationObserver?.disconnect()
    window.removeEventListener('resize', schedule)
    document.removeEventListener('scroll', schedule, true)
  }
}

/** Edge hit zone (px) that starts a panel resize drag. Wide enough to grab
 *  without hunting: a window edge is a thin target on a scaled display. */
const RESIZE_EDGE = 14
/** The mobile sheet has no four-edge resize interaction. */
const MOBILE_BREAKPOINT = 768
/** Smallest panel size a resize drag can produce. */
const RESIZE_MIN_WIDTH = 196
const RESIZE_MIN_HEIGHT = 120
/** Rail gap the panel keeps from the transcript when pushed or sized. */
const PANEL_GAP = 18
/** Top inset a floating window keeps from the viewport edge. */
const PANEL_TOP_FLOOR = 12

/**
 * Top of the sticky composer, or the viewport floor when it is absent. Windows
 * use it as their lower bound, so a placed window never covers the input.
 * @returns the composer's top edge in viewport pixels.
 */
function composerCeiling(): number {
  const composer = document.querySelector<HTMLElement>("[data-phase] [class*='composerSeat']")
  return composer?.getBoundingClientRect().top ?? window.innerHeight - 140
}
/** Step a settled window snaps to, so dropped windows line up. */
const SNAP_STEP = 8
/** Step each newly opened window is offset by, so a stack of windows reads. */
const CASCADE_STEP = 28
/** The cascade stops widening after this many open windows. */
const CASCADE_LIMIT = 8
/** Z-index the first activated window takes; each activation takes the next. */
const PANEL_BASE_Z = 41

let topPanelZ = PANEL_BASE_Z

/**
 * The windows currently floating over the transcript: every portalled detail
 * surface plus any panel pinned inside the message flow. Minimized windows are
 * parked in the dock and read as closed.
 * @returns the visible floating windows, in document order.
 */
function floatingWindows(): HTMLElement[] {
  const out: HTMLElement[] = []
  for (const panel of document.querySelectorAll<HTMLElement>(WINDOW_SELECTOR)) {
    if (panel.hasAttribute('data-dsh-panel-minimized')) continue
    const floats = panel.hasAttribute('data-dsh-code-floating')
      || panel.closest('[data-dsh-detail-overlay-root]') !== null
      || panel.closest('[data-dsh-panel-pinned="true"]') !== null
    if (floats) out.push(panel)
  }
  return out
}

/**
 * Raise one window above every other. Windows are independent surfaces: each is
 * placed, sized, and pinned on its own, and the last one the user pressed is the
 * one that reads on top.
 * @param panel - the window to activate.
 */
function raisePanel(panel: HTMLElement): void {
  topPanelZ += 1
  panel.style.setProperty('--dsh-panel-z', String(topPanelZ))
  for (const other of document.querySelectorAll<HTMLElement>('[data-dsh-panel-active="true"]')) {
    if (other !== panel) other.removeAttribute('data-dsh-panel-active')
  }
  panel.setAttribute('data-dsh-panel-active', 'true')
}

/**
 * Snap a length to the shared window grid.
 * @param value - length in pixels.
 * @returns the nearest grid step.
 */
function snapLength(value: number): number {
  return Math.round(value / SNAP_STEP) * SNAP_STEP
}

interface ResizeDrag {
  pointerId: number
  panel: HTMLElement
  startX: number
  startY: number
  originWidth: number
  originHeight: number
  originLeft: number
  originTop: number
  lastWidth: number
  lastHeight: number
  lastLeft: number
  lastTop: number
  east: boolean
  west: boolean
  south: boolean
  north: boolean
}

/** The surfaces that accept a window-style resize drag: a detached code block,
 *  a Think dossier, a portalled tool detail, or a pinned code panel. Inline code
 *  bodies stay in the message flow and keep their natural width. */
function resizablePanel(target: Element): HTMLElement | null {
  if (typeof window !== 'undefined' && window.innerWidth <= MOBILE_BREAKPOINT) return null
  const panel = target.closest<HTMLElement>(WINDOW_SELECTOR)
  if (panel === null) return null
  // A maximized window is placed by the stylesheet band above the composer;
  // an edge drag would fight that placement and leave a stale user size.
  if (panel.hasAttribute('data-dsh-panel-maximized')) return null
  // A surface the user already detached is a window and takes an edge drag.
  if (panel.hasAttribute('data-dsh-code-floating')) return panel
  if (panel.matches('[class*="thinkBody"]')) return panel
  if (panel.closest('[data-dsh-detail-overlay-root]') !== null) return panel
  if (panel.getAttribute('data-dsh-detail-panel') === 'tool') return panel
  return panel.closest('[data-dsh-panel-pinned="true"]') !== null ? panel : null
}

/**
 * Window-style panel resizing. A drag that starts inside the panel's edge zone
 * resizes that panel through CSS variables (the window rules consume
 * `--dsh-panel-width` / `--dsh-panel-height`), and the settled size snaps to
 * the shared window grid. Windows never move each other: the only thing a
 * window changes outside itself is the transcript's avoidance inset, which the
 * layout pass derives from how far the window reaches over the readable column.
 * @returns a disposer that removes all listeners.
 */
function installArcadePanelResize(): () => void {
  if (typeof document === 'undefined') return () => {}
  let drag: ResizeDrag | null = null

  const clampToViewport = (
    panel: HTMLElement,
    width: number,
    height: number,
    west: boolean,
    north: boolean,
  ): { width: number; height: number } => {
    const rect = panel.getBoundingClientRect()
    /* v8 ignore next -- jsdom innerWidth (1024) always clears the minimum */
    const maxWidth = Math.max(RESIZE_MIN_WIDTH, (west ? rect.right : window.innerWidth) - (west ? 12 : rect.left + 12))
    const ceiling = composerCeiling()
    const maxHeight = Math.max(
      RESIZE_MIN_HEIGHT,
      (north ? rect.bottom : ceiling - rect.top) - PANEL_GAP,
    )
    return { width: Math.min(width, maxWidth), height: Math.min(height, maxHeight) }
  }

  const onPointerDown = (event: PointerEvent): void => {
    if (event.button !== 0) return
    const target = event.target
    if (!(target instanceof Element)) return
    // A detachable code block's banner is its toggle and drag handle, and it
    // sits inside the block's top edge: yielding it keeps the two gestures from
    // claiming the same press.
    if (target.closest('button, [data-dsh-drag-handle], [class*="bannerWrap"], textarea, input, a') !== null) return
    const panel = resizablePanel(target)
    if (panel === null) return
    const rect = panel.getBoundingClientRect()
    const east = event.clientX >= rect.right - RESIZE_EDGE
    const west = event.clientX <= rect.left + RESIZE_EDGE
    const south = event.clientY >= rect.bottom - RESIZE_EDGE
    const north = event.clientY <= rect.top + RESIZE_EDGE
    if (!east && !west && !south && !north) return
    raisePanel(panel)
    drag = {
      pointerId: event.pointerId,
      panel,
      startX: event.clientX,
      startY: event.clientY,
      originWidth: rect.width,
      originHeight: rect.height,
      originLeft: rect.left,
      originTop: rect.top,
      lastWidth: rect.width,
      lastHeight: rect.height,
      lastLeft: rect.left,
      lastTop: rect.top,
      east,
      west,
      south,
      north,
    }
    // Pointer capture keeps the gesture alive when the pointer leaves the
    // window. It is an enhancement, not a precondition: an environment without
    // the surface (older engines, a test DOM) must still get the resize.
    if (typeof panel.setPointerCapture === 'function') panel.setPointerCapture(event.pointerId)
    panel.setAttribute('data-dsh-resizing', 'true')
    event.preventDefault()
  }

  const onPointerMove = (event: PointerEvent): void => {
    if (drag === null || event.pointerId !== drag.pointerId) return
    const dx = event.clientX - drag.startX
    const dy = event.clientY - drag.startY
    let width = drag.originWidth
    let height = drag.originHeight
    if (drag.east) width = drag.originWidth + dx
    if (drag.west) width = drag.originWidth - dx
    if (drag.south) height = drag.originHeight + dy
    if (drag.north) height = drag.originHeight - dy
    width = Math.max(RESIZE_MIN_WIDTH, width)
    height = Math.max(RESIZE_MIN_HEIGHT, height)
    const clamped = clampToViewport(drag.panel, width, height, drag.west, drag.north)
    // A west or north drag anchors the OPPOSITE edge: the position absorbs the
    // size change, so the edge the user is not holding stays put. Deriving the
    // position from the clamped size also stops the held edge once the minimum
    // size is reached, instead of letting it slide on alone.
    let left = drag.west ? drag.originLeft + (drag.originWidth - clamped.width) : drag.originLeft
    let top = drag.north ? drag.originTop + (drag.originHeight - clamped.height) : drag.originTop
    if (left < 0) left = 0
    if (top < 0) top = 0
    drag.lastWidth = clamped.width
    drag.lastHeight = clamped.height
    drag.lastLeft = left
    drag.lastTop = top
    drag.panel.style.setProperty('--dsh-panel-width', `${Math.round(clamped.width)}px`)
    drag.panel.style.setProperty('--dsh-panel-height', `${Math.round(clamped.height)}px`)
    // The resting ceiling must admit the size the user just dragged out, or
    // dropping data-dsh-resizing snaps the window back to the rail default.
    drag.panel.style.setProperty('--dsh-panel-max-height', `${Math.round(clamped.height)}px`)
    if (drag.west) drag.panel.style.setProperty('--dsh-panel-left', `${Math.round(left)}px`)
    if (drag.north) drag.panel.style.setProperty('--dsh-panel-top', `${Math.round(top)}px`)
  }

  const onPointerUp = (event: PointerEvent): void => {
    if (drag === null || event.pointerId !== drag.pointerId) return
    const { panel, lastWidth, lastHeight, lastLeft, lastTop, west, north } = drag
    drag = null
    if (typeof panel.hasPointerCapture === 'function' && panel.hasPointerCapture(event.pointerId)) {
      panel.releasePointerCapture(event.pointerId)
    }
    panel.removeAttribute('data-dsh-resizing')
    if (!panel.isConnected) return
    // The stylesheet owns the size through --dsh-panel-width/height, but a
    // product re-render would rewrite those from its own pinned snapshot.
    // Report the settled size so the product state follows the drag.
    panel.dispatchEvent(new CustomEvent('dsh-panel-resized', {
      bubbles: true,
      detail: {
        width: Math.round(lastWidth),
        height: Math.round(lastHeight),
        // A west or north drag moved the window's own edge, so the product has
        // to store the new position too or the next render snaps it back.
        ...(west ? { left: Math.round(lastLeft) } : {}),
        ...(north ? { top: Math.round(lastTop) } : {}),
      },
    }))
  }

  // Edge-zone cursor feedback while hovering (no active drag).
  const onHoverMove = (event: PointerEvent): void => {
    if (drag !== null) return
    const target = event.target
    if (!(target instanceof Element)) return
    const panel = resizablePanel(target)
    if (panel === null) return
    const rect = panel.getBoundingClientRect()
    const east = event.clientX >= rect.right - RESIZE_EDGE
    const west = event.clientX <= rect.left + RESIZE_EDGE
    const south = event.clientY >= rect.bottom - RESIZE_EDGE
    const north = event.clientY <= rect.top + RESIZE_EDGE
    const cursor = east && south ? 'nwse-resize'
      : west && south ? 'nesw-resize'
        : east && north ? 'nesw-resize'
          : west && north ? 'nwse-resize'
            : east || west ? 'ew-resize'
              : south || north ? 'ns-resize'
                : ''
    panel.style.cursor = cursor
    if (cursor === '') {
      panel.style.removeProperty('cursor')
    }
  }

  document.addEventListener('pointerdown', onPointerDown, true)
  document.addEventListener('pointermove', onPointerMove, true)
  document.addEventListener('pointerup', onPointerUp, true)
  document.addEventListener('pointercancel', onPointerUp, true)
  document.addEventListener('pointermove', onHoverMove, true)
  return () => {
    document.removeEventListener('pointerdown', onPointerDown, true)
    document.removeEventListener('pointermove', onPointerMove, true)
    document.removeEventListener('pointerup', onPointerUp, true)
    document.removeEventListener('pointercancel', onPointerUp, true)
    document.removeEventListener('pointermove', onHoverMove, true)
  }
}

/**
 * Click-to-front window layering. Pressing anywhere in a floating window raises
 * it above the others, so the surface the user is reading or working in is the
 * one that reads on top. Windows are otherwise independent: raising one never
 * moves, resizes, or hides another.
 * @returns a disposer that removes the listener.
 */
function installArcadePanelFocus(): () => void {
  if (typeof document === 'undefined') return () => {}
  const onPointerDown = (event: PointerEvent): void => {
    if (event.button !== 0) return
    const target = event.target
    if (!(target instanceof Element)) return
    const panel = target.closest<HTMLElement>(WINDOW_SELECTOR)
    if (panel === null) return
    raisePanel(panel)
  }
  document.addEventListener('pointerdown', onPointerDown, true)
  return () => { document.removeEventListener('pointerdown', onPointerDown, true) }
}

/** Per-panel window-chrome record kept by the dock while a panel is parked. */
interface DockEntry {
  side: 'left' | 'right'
  title: string
}

/**
 * Window chrome for every floating detail surface: the theme runtime answers
 * `dsh-panel-command` events (minimize/maximize) dispatched by the product
 * toolbar buttons, hiding minimized panels into taskbar docks on both free
 * flanks of the transcript. Each dock button opens a list of the parked
 * panels; picking one restores it. State lives in data attributes the CSS
 * consumes, so the product components never need to know about the chrome.
 * @returns a disposer that removes docks and listeners.
 */
function installArcadeWindowChrome(): () => void {
  if (typeof document === 'undefined') return () => {}
  const entries = new WeakMap<HTMLElement, DockEntry>()
  let dockLeft: HTMLElement | null = null
  let dockRight: HTMLElement | null = null
  let listOpen: 'left' | 'right' | null = null

  const dockFor = (side: 'left' | 'right'): HTMLElement => {
    if (side === 'left' && dockLeft !== null) return dockLeft
    if (side === 'right' && dockRight !== null) return dockRight
    const dock = document.createElement('div')
    dock.className = 'rizen-dock'
    dock.setAttribute('data-side', side)
    dock.setAttribute('data-empty', 'true')
    document.body.appendChild(dock)
    if (side === 'left') dockLeft = dock
    else dockRight = dock
    return dock
  }

  const panelTitle = (panel: HTMLElement): string => {
    const row = panel.closest<HTMLElement>('[data-tool], [data-variant="think"]')
    const title = row === null ? null : row.querySelector<HTMLElement>('[class*="title"]')
    const text = title !== null
      ? title.textContent.trim()
      : row !== null
        ? row.textContent.trim()
        : panel.textContent.trim()
    return text.slice(0, 24) || '面板'
  }

  const panelSideOf = (panel: HTMLElement): 'left' | 'right' => {
    const row = panel.closest<HTMLElement>('[data-dsh-panel-side]')
    if (row?.getAttribute('data-dsh-panel-side') === 'right') return 'right'
    const rect = panel.getBoundingClientRect()
    if (rect.width > 0) {
      return rect.left + rect.width / 2 < window.innerWidth / 2 ? 'left' : 'right'
    }
    return 'left'
  }

  const minimizedPanels = (side: 'left' | 'right'): HTMLElement[] => {
    const out: HTMLElement[] = []
    for (const panel of document.querySelectorAll<HTMLElement>(WINDOW_MINIMIZED_SELECTOR)) {
      // A panel whose attribute was set directly (not via a command) has no
      // recorded side; park it on the default left rail.
      const panelSide = entries.get(panel)?.side ?? 'left'
      if (panelSide === side) out.push(panel)
    }
    return out
  }

  const restore = (panel: HTMLElement): void => {
    panel.removeAttribute('data-dsh-panel-minimized')
    entries.delete(panel)
  }

  const toggleList = (side: 'left' | 'right'): void => {
    listOpen = listOpen === side ? null : side
    syncDock()
  }

  const syncDock = (): void => {
    // The attribute observer may fire after the jsdom environment is torn
    // down between vitest files; without the DOM there is no dock to update.
    if (typeof document === 'undefined') return
    for (const side of ['left', 'right'] as const) {
      const dock = dockFor(side)
      const parked = minimizedPanels(side)
      dock.setAttribute('data-empty', parked.length === 0 ? 'true' : 'false')
      dock.textContent = ''
      if (parked.length === 0) continue
      const button = document.createElement('button')
      button.type = 'button'
      button.className = 'rizen-dock-button'
      button.textContent = `${parked.length} ▤`
      button.setAttribute('aria-label', `最小化面板 ${parked.length} 个`)
      button.setAttribute('data-open', listOpen === side ? 'true' : 'false')
      button.addEventListener('click', () => { toggleList(side) })
      dock.appendChild(button)
      if (listOpen === side) {
        const list = document.createElement('div')
        list.className = 'rizen-dock-list'
        for (const panel of parked) {
          const item = document.createElement('button')
          item.type = 'button'
          item.className = 'rizen-dock-item'
          item.textContent = entries.get(panel)?.title ?? panelTitle(panel)
          item.addEventListener('click', () => { restore(panel); toggleList(side) })
          list.appendChild(item)
        }
        dock.appendChild(list)
      }
    }
  }

  const onCommand = (event: Event): void => {
    const target = event.target
    if (!(target instanceof Element)) return
    const panel = target.closest<HTMLElement>(WINDOW_SELECTOR)
    if (panel === null) return
    const command = (event as CustomEvent).detail as { command?: string } | undefined
    if (command?.command === 'minimize') {
      if (!entries.has(panel)) {
        entries.set(panel, { side: panelSideOf(panel), title: panelTitle(panel) })
      }
      panel.setAttribute('data-dsh-panel-minimized', 'true')
      listOpen = null
      syncDock()
    } else if (command?.command === 'maximize') {
      if (panel.hasAttribute('data-dsh-panel-maximized')) {
        panel.removeAttribute('data-dsh-panel-maximized')
      } else {
        panel.setAttribute('data-dsh-panel-maximized', 'true')
        // A maximized window shows its content from the top; the panel may
        // have scrolled while it was pinned or inline.
        panel.scrollTop = 0
      }
    }
  }

  const onOutsidePointer = (event: Event): void => {
    if (listOpen === null) return
    const target = event.target
    if (target instanceof Element && target.closest('.rizen-dock') !== null) return
    listOpen = null
    syncDock()
  }

  const mutationObserver = typeof MutationObserver === 'undefined'
    ? undefined
    : new MutationObserver(() => { syncDock() })
  mutationObserver?.observe(document.body, { attributes: true, subtree: true, attributeFilter: ['data-dsh-panel-minimized'] })
  document.addEventListener('dsh-panel-command', onCommand, true)
  document.addEventListener('pointerdown', onOutsidePointer, true)
  syncDock()
  return () => {
    mutationObserver?.disconnect()
    document.removeEventListener('dsh-panel-command', onCommand, true)
    document.removeEventListener('pointerdown', onOutsidePointer, true)
    dockLeft?.remove()
    dockRight?.remove()
    dockLeft = null
    dockRight = null
  }
}

interface BodyDrag {
  pointerId: number
  panel: HTMLElement
  startX: number
  startY: number
  originX: number
  originY: number
  moved: boolean
}

/** Drag threshold (px) before a body press becomes a panel move. */
const BODY_DRAG_THRESHOLD = 6

/**
 * Android-widget style moving: pressing inside a floating panel body — a
 * non-interactive area that carries neither prose nor code — and dragging
 * floats the panel at the pointer position. On release an unpinned panel is
 * pinned through the product's own pin button so the transcript yields its
 * rail; an already-pinned panel reports its settled position instead, because
 * its button now offers the unpin action. Either way the temporary inline
 * positioning is cleared and the pinned rail rules take over.
 * @returns a disposer that removes all listeners.
 */
function installArcadePanelBodyDrag(): () => void {
  if (typeof document === 'undefined') return () => {}
  let drag: BodyDrag | null = null

  const onPointerDown = (event: PointerEvent): void => {
    if (event.button !== 0) return
    const target = event.target
    if (!(target instanceof Element)) return
    // Panel prose and tool output stay selectable: a press that lands on
    // readable content is a text gesture, not a window move.
    if (target.closest('button, [data-dsh-drag-handle], textarea, input, a, pre, code, [data-dsh-content-area], [class*="code"]') !== null) return
    const panel = target.closest<HTMLElement>(WINDOW_SELECTOR)
    if (panel === null) return
    const rect = panel.getBoundingClientRect()
    if (rect.width === 0 || rect.height === 0) return
    // The resize installer listens on the same capture phase. Reserve the
    // outer edge zone for resizing so body dragging cannot rewrite position
    // while a width or height drag is active.
    const onEdge = event.clientX <= rect.left + RESIZE_EDGE
      || event.clientX >= rect.right - RESIZE_EDGE
      || event.clientY <= rect.top + RESIZE_EDGE
      || event.clientY >= rect.bottom - RESIZE_EDGE
    if (onEdge) return
    drag = {
      pointerId: event.pointerId,
      panel,
      startX: event.clientX,
      startY: event.clientY,
      originX: rect.left,
      originY: rect.top,
      moved: false,
    }
    // Stop the browser from starting a text selection during a move.
    event.preventDefault()
  }

  const onPointerMove = (event: PointerEvent): void => {
    if (drag === null || event.pointerId !== drag.pointerId) return
    const dx = event.clientX - drag.startX
    const dy = event.clientY - drag.startY
    if (!drag.moved && Math.abs(dx) < BODY_DRAG_THRESHOLD && Math.abs(dy) < BODY_DRAG_THRESHOLD) return
    drag.moved = true
    const panel = drag.panel
    const rect = panel.getBoundingClientRect()
    // Keep the window on the page and clear of the composer: a window dragged
    // over the input console would cover the control the user is typing into.
    const left = Math.min(Math.max(0, drag.originX + dx), Math.max(0, window.innerWidth - rect.width))
    const top = Math.min(Math.max(0, drag.originY + dy), Math.max(0, composerCeiling() - PANEL_GAP - rect.height))
    panel.style.position = 'fixed'
    panel.style.left = `${Math.round(left)}px`
    panel.style.top = `${Math.round(top)}px`
    panel.style.right = 'auto'
    panel.style.bottom = 'auto'
    panel.style.margin = '0'
    panel.style.zIndex = '40'
    panel.style.userSelect = 'none'
    panel.setAttribute('data-dsh-body-dragging', 'true')
  }

  const finishDrag = (event: PointerEvent): void => {
    if (drag === null || event.pointerId !== drag.pointerId) return
    const { panel } = drag
    drag = null
    panel.style.removeProperty('userSelect')
    panel.removeAttribute('data-dsh-body-dragging')
    if (!panel.isConnected) return
    // Settle onto the shared grid and keep the window on the page, so windows
    // dropped near each other line up instead of landing on arbitrary pixels.
    const placed = panel.getBoundingClientRect()
    panel.style.left = `${Math.min(Math.max(0, snapLength(placed.left)), Math.max(0, window.innerWidth - placed.width))}px`
    panel.style.top = `${Math.max(0, snapLength(placed.top))}px`
    // An unpinned window hands the final position to the product's pin action,
    // which captures the moved rect. An already-pinned window has no pin
    // action left to click, so it reports the settled position instead of
    // snapping back to its previous offset.
    const pinButton = panel.querySelector<HTMLButtonElement>('button[aria-label="固定面板"]')
    if (pinButton === null) {
      const settled = panel.getBoundingClientRect()
      panel.dispatchEvent(new CustomEvent('dsh-panel-moved', {
        bubbles: true,
        detail: { left: Math.round(settled.left), top: Math.round(settled.top) },
      }))
    } else {
      pinButton.click()
    }
    // Clear the temporary inline placement once the product re-renders with
    // its own --dsh-panel-* variables (the pinned rules take over).
    window.setTimeout(() => {
      if (!panel.isConnected) return
      panel.style.removeProperty('position')
      panel.style.removeProperty('left')
      panel.style.removeProperty('top')
      panel.style.removeProperty('right')
      panel.style.removeProperty('bottom')
      panel.style.removeProperty('margin')
      panel.style.removeProperty('zIndex')
    }, 60)
  }

  const onPointerUp = (event: PointerEvent): void => { finishDrag(event) }
  const onPointerCancel = (event: PointerEvent): void => { finishDrag(event) }

  document.addEventListener('pointerdown', onPointerDown, true)
  document.addEventListener('pointermove', onPointerMove, true)
  document.addEventListener('pointerup', onPointerUp, true)
  document.addEventListener('pointercancel', onPointerCancel, true)
  return () => {
    document.removeEventListener('pointerdown', onPointerDown, true)
    document.removeEventListener('pointermove', onPointerMove, true)
    document.removeEventListener('pointerup', onPointerUp, true)
    document.removeEventListener('pointercancel', onPointerCancel, true)
  }
}

/**
 * Let a fenced code block in the reply detach into a floating window, and move
 * it again once detached. The block's banner is both the toggle and the drag
 * handle: a press that never moves toggles the window, a press that moves drags
 * it. The banner is the only control surface a code block has, and it sits in
 * the block's top edge, so the resize installer stands off it entirely.
 *
 * Nothing is injected into React's tree — the state rides an attribute the
 * stylesheet reads — because a node added to a managed subtree would be
 * discarded on the next re-render. The copy control keeps its own gesture, and
 * a press in the code body stays a text gesture.
 * @returns a disposer that removes the listeners.
 */
function installArcadeCodeFloat(): () => void {
  if (typeof document === 'undefined') return () => {}
  interface CodeGesture {
    block: HTMLElement
    pointerId: number
    x: number
    y: number
    startLeft: number
    startTop: number
    moved: boolean
  }
  let gesture: CodeGesture | null = null

  const onPointerDown = (event: PointerEvent): void => {
    if (event.button !== 0) return
    const target = event.target
    if (!(target instanceof Element)) return
    if (target.closest('button') !== null) return
    const banner = target.closest<HTMLElement>('[class*="bannerWrap"] > [class*="banner"]')
    if (banner === null) return
    const block = banner.closest<HTMLElement>('.md-code-block')
    if (block === null) return
    const rect = block.getBoundingClientRect()
    gesture = {
      block,
      pointerId: event.pointerId,
      x: event.clientX,
      y: event.clientY,
      startLeft: rect.left,
      startTop: rect.top,
      moved: false,
    }
  }

  const onPointerMove = (event: PointerEvent): void => {
    if (gesture === null || event.pointerId !== gesture.pointerId) return
    const dx = event.clientX - gesture.x
    const dy = event.clientY - gesture.y
    if (!gesture.moved && Math.abs(dx) < BODY_DRAG_THRESHOLD && Math.abs(dy) < BODY_DRAG_THRESHOLD) return
    // Only a detached block moves: while it is still in the flow the gesture is
    // still a candidate click, and the block keeps its place until release.
    if (!gesture.block.hasAttribute('data-dsh-code-floating')) return
    gesture.moved = true
    const block = gesture.block
    const rect = block.getBoundingClientRect()
    const left = Math.min(Math.max(0, gesture.startLeft + dx), Math.max(0, window.innerWidth - rect.width))
    const top = Math.min(Math.max(0, gesture.startTop + dy), Math.max(0, composerCeiling() - PANEL_GAP - rect.height))
    block.style.setProperty('--dsh-panel-left', `${Math.round(left)}px`)
    block.style.setProperty('--dsh-panel-top', `${Math.round(top)}px`)
  }

  const onPointerUp = (event: PointerEvent): void => {
    if (gesture === null || event.pointerId !== gesture.pointerId) return
    const { block, moved } = gesture
    gesture = null
    if (moved) return
    if (block.hasAttribute('data-dsh-code-floating')) {
      block.removeAttribute('data-dsh-code-floating')
      // The cascade offset was assigned to the detached window; a block back in
      // the flow must not carry it into its next detach.
      block.style.removeProperty('--dsh-panel-cascade')
      return
    }
    block.setAttribute('data-dsh-code-floating', '')
  }

  document.addEventListener('pointerdown', onPointerDown, true)
  document.addEventListener('pointermove', onPointerMove, true)
  document.addEventListener('pointerup', onPointerUp, true)
  document.addEventListener('pointercancel', onPointerUp, true)
  return () => {
    document.removeEventListener('pointerdown', onPointerDown, true)
    document.removeEventListener('pointermove', onPointerMove, true)
    document.removeEventListener('pointerup', onPointerUp, true)
    document.removeEventListener('pointercancel', onPointerUp, true)
  }
}

/** Every installer this runtime owns, in install order. The skin plugin mounts
 *  the same roster standalone, so the list lives inside the extracted block. */
const ARCADE_RUNTIME_INSTALLERS = [
  installArcadePointerFeedback,
  installArcadePanelLayout,
  installArcadePanelResize,
  installArcadePanelFocus,
  installArcadeWindowChrome,
  installArcadePanelBodyDrag,
  installArcadeCodeFloat,
] as const

/**
 * Page-global install marker, shared verbatim with the Harness personal theme
 * patch. Both bundles may be present (a developer running the patched checkout
 * plus this skin); the page is the only place they can coordinate, so whichever
 * installs second stands down instead of doubling every document listener.
 */
const ARCADE_RUNTIME_FLAG = '__dshArcadeWindowRuntime'

/** Cordis plugin name. */
export const name = 'dsh-skin-digital-arcade-windows'

/** The runtime needs no Harness services: it observes the DOM directly. */
export const inject = []

/**
 * Mount the window runtime, once per page.
 * @param ctx - client plugin context providing `effect`.
 */
export function apply(ctx) {
  const host = globalThis
  if (host[ARCADE_RUNTIME_FLAG] === true) return
  host[ARCADE_RUNTIME_FLAG] = true
  ctx.effect(() => {
    const disposers = ARCADE_RUNTIME_INSTALLERS.map(install => install())
    return () => {
      for (const dispose of disposers) dispose()
      delete host[ARCADE_RUNTIME_FLAG]
    }
  }, 'dsh-skin-digital-arcade: window runtime')
}
